# fly.toml app configuration file generated for fullstack-cicd-blogapp on 2024-12-12T14:23:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-cicd-blogapp'
primary_region = 'arn'

[build]

[env]
  PORT = 3003

[processes]
  app = "node server/index.js"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
