name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install && npm install --prefix client && npm install --prefix server
      - name: ESLint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test client
        run: npm run test:client
      - name: Create .env file
        run: |
          touch server/.env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> server/.env
          echo "TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}" >> server/.env
          echo "PORT=${{ secrets.PORT }}" >> server/.env
          echo "SECRET=${{ secrets.SECRET }}" >> server/.env
      - name: Test server
        run: npm run test:server
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: E2E Tests
        run: |
          npm run server:test &
          npm run test:e2e
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
